FROM node:20-alpine AS builder
# Set working directory
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json turbo.json ./
COPY apps/backend/package.json ./apps/backend/
RUN npm ci

# Copy source code and build
COPY . .
RUN npx turbo run build --filter=@dtc/backend

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app /app
WORKDIR /app/apps/backend

EXPOSE 9000
CMD ["npm", "run", "start"]
